#### GET al home
GET http://localhost:3008

#### GET a los dispositivos
GET http://localhost:3008/electronicos

#### GET para obtenet dispositivo por id  
GET http://localhost:3008/electronicos/

#### GET para obtenet dispositivo por nombre
GET http://localhost:3008/electronicos/nombre/heladera

#### POST para agregar un nuevo dispositivo
POST http://localhost:3008/electronicos

#### PATCH para modificar un dispositivo
PATCH http://localhost:3008/electronicos/:id

#### DELETE para borrar un dispositivo
DELETE http://localhost:3008/electronicos/668fe3a5978a595530d343d9

