#### GET al home
GET http://localhost:3008

#### GET a los dispositivos
GET http://localhost:3008/electronicos

#### GET para obtenet dispositivo por id  
GET http://localhost:3008/electronicos/:id

#### GET para obtenet dispositivo por nombre
GET http://localhost:3008/electronicos/nombre/heladera

#### POST para agregar un nuevo dispositivo
POST http://localhost:3008/electronicos

#### PATCH para modificar un dispositivo
PATCH http://localhost:3008/electronicos/

#### DELETE para borrar un dispositivo
DELETE http://localhost:3008/electronicos/6690212c8974f3a03d60874f

